void change_dir(char * newdir);
char ** parse_args( char * line);
int runCmd(char * buffer);
int checkMultipleCmds(char * line);
char ** multipleCmds(char * line);
char * processCharacters(char ** commandList,int commandListLen);
void revertTermios(struct termios termy);
void changeTermios(struct termios * termy);
void getCursorXY(int * x, int * y);
void moveCursorRight(int * currentX, int * currentY, int totalRow, int totalCol, int  * initial);
int moveCursorLeft(int * currentX, int * currentY, int initialX, int initialY,int totalCol);
void deleteIndex(char ** buffer, int * index);
int * returnPointFromMatrix(int initialX, int initialY, int totalRow, int totalCol, int len);
void addIndex(char ** buffer, int * index, char value);
void insertBeginning(char *** multiArray, char * command, int lastIndex);
int redirect(char * buffer);
int existsRedirection(char * buffer);
char * stripwhitespace(char * arr);
char * doubleRedirect(char * moreRedirect,int * isTrue,int * newfd, int  * oldfd, int * openFile);
int isPipe(char * buffer);
int pipeCommands(char * buffer);
void insertString(char ** buffer, int indexTilde, char * value, int newSize);
void replaceExtraStringWithTilde(char ** buffer, char * valueToSearch, int newSize);
